version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5178:5178"
    environment:
      - HOST=0.0.0.0
      - PORT=5178
    volumes:
      - .:/app
      - /app/node_modules
