version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5177:5177"
    environment:
      - HOST=0.0.0.0
      - PORT=5177
    volumes:
      - .:/app
      - /app/node_modules
