version: '3.8'

services:
  react-app:
    container_name: kwickbill-ui-app-development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5177:5177"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

volumes:
  node_modules:
